version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finance_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

  api:
    build: .
    container_name: finance_api
    ports:
      - "3006:3006"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/finance_db
      JWT_SECRET: supersecretkey
      PORT: 3006
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm start"
    networks:
      - finance-network

volumes:
  postgres_data:


networks:
  finance-network:
    driver: bridge
