version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finance_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

  api:
    build: .
    container_name: finance_api
    ports:
      - "3006:3006"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/finance_db
      JWT_SECRET: supersecretkey
      PORT: 3006
    depends_on:
      - postgres
    command: sh -c "npx prisma db push --accept-data-loss && npm start"
    networks:
      - finance-network

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WHATSAPP_HOOK_EVENTS: message
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3009:3000"
    networks:
      - finance-network

volumes:
  postgres_data:
  waha_sessions:
  waha_media:


networks:
  finance-network:
    driver: bridge
